# Generated by Django 4.1.3 on 2022-12-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecuritySystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='WORKERS',
        ),
    ]
