# Generated by Django 4.1.3 on 2022-12-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecuritySystem', '0002_rename_employee_workers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='roll',
            new_name='location',
        ),
    ]
