# Generated by Django 4.1.3 on 2022-12-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuritySystem', '0003_rename_roll_workers_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEMBERSHIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnails', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('qty', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='WORKERS',
        ),
    ]
