# Generated by Django 4.1.3 on 2022-12-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuritySystem', '0004_membership_delete_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WORKERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MEMBERSHIP',
        ),
    ]
